export enum IconNames {
  bar = 'bar',
  cuisine = 'cuisine',
  brightness = 'brightness',
  cherry = 'cherry',
  clock = 'clock',
  dish = 'dish',
  email = 'email',
  location = 'location',
  menu = 'menu',
  recommended = 'recommended',
  service = 'service',
  website = 'website',
  tripadvisor = 'tripadvisor',
  whatsapp = 'whatsapp',
  tiktok = 'tiktok',
  instagram = 'instagram',
  facebook = 'facebook',
  sushi = 'sushi',
  back = 'back',
  top = 'top',
  down = 'down',
  home = 'home',
  vegetarian = 'vegetarian',
  spicy = 'spicy',
}
