export enum EScreens {
  HOME_SCREEN = 'HOME_SCREEN',
  MAIN_SCREEN = 'MAIN_SCREEN',
  CATEGORY_SCREEN = 'CATEGORY_SCREEN',
  MENU_SCREEN = 'MENU_SCREEN',
  POSITION_DETAILS_SCREEN = 'POSITION_DETAILS_SCREEN',
}
